[package]
name = "SelfDrivingYield"
version = "0.1.0"
edition = "2024"

[dependencies]
CetusClmm = { git = "https://github.com/CetusProtocol/cetus-contracts.git", subdir = "packages/cetus_clmm", rev = "mainnet-v0.14.0" }

[addresses]
self_driving_yield = "0x0"
